### PR TITLE
Improved support for variables names with spaces in them

### PR DESCRIPTION
**Pull request by jonathon-love**
Fixes jamovi/jmv#131

Hi Russell,

I'm not completely sure of the implications of this, it's possible this will break something else, but it does past all the tests.

with thanks

Jonathon

### CODE REVIEW

**Comment by rvlenth** [comment]
Thanks, Jonathon. I had to rename `reformulate` to make other things work, and I believe I failed to rename the call to it as you did in this request. I'm merging it in and hoping for the best

**Comment by rvlenth** [comment]
A remaining issue with this is that, while we can do `emmeans()` just fine, `emmip()` will not work with spaced variable names because it needs to use the `stats` version of `reformulate()`. I guess the way to make it work would be to provide an alternative way to specify the plot besides `formula`. It may be a lot of extra work for not much benefit though.

**Comment by rvlenth** [comment]
I think I have ironed-out all issues with such fancy names. With my next push to github, one may now use `emmeans()` with formula specs, as well as `emmip()` with such models. The only exceptions would be model classes that don't use `recover_data()` method for class `"call"`. I can't remember if there are any such cases.

Thanks again, Jonathon!

**Comment by jonathon-love** [comment]
Great Russell! works a charm!

Let me know when you push to CRAN, there's a couple of packages affected by this (because we're using `emmeans` with [jamovi](https://www.jamovi.org), and it's a spreadsheet, people are more likely to use spaces in column names, which is why it's been as issue for us, but probably not for your traditional user-base).

In other news, transitioning to `emmeans` from `lsmeans` went without a hitch.

with thanks

**Pull request merged**
