### PR TITLE
Fix ref_grid with missing levels

### LINKED ISSUE #508: Inconsistent results with missing levels since #500
Hello Russel,

I've found this inconsistency described below. I'm still looking into it and I haven't managed to come up with a solution yet, but I wanted to let you know.

## Describe the bug
Since the changes in #500 contrasts are generated differently for a dataset with missing levels whether `data` argument is used in `emmeans` or not. I suppose without the `data` argument `recover_data()` is generating the actually appearing levels, but with `data` the non-existent level is appearing among the contrasts (level `c` in the example below).

## To reproduce
``` r
library(emmeans)
#> Welcome to emmeans.
#> Caution: You lose important information if you filter this package's results.
#> See '? untidy'

x <- data.frame(
  group = factor(c("a", "a", "b", "b"), levels = c("a", "b", "c")),
  value = 1:4
)
x$group
#> [1] a a b b
#> Levels: a b c
m <- lm(value ~ group, data = x)

# default (allow.na.levs = TRUE)
options(emmeans = list())
em1 <- emmeans(m, ~ group)
contrast(em1, "pairwise")
#>  contrast estimate    SE df t.ratio p.value
#>  a - b          -2 0.707  2  -2.828  0.1056
em2 <- emmeans(m, ~ group, data = x)
contrast(em2, "pairwise")
#>  contrast estimate    SE df t.ratio p.value
#>  a - b          -2 0.707  2  -2.828  0.1534
#>  a - c           0 0.000  2     NaN     NaN
#>  b - c           2 0.707  2   2.828  0.1534
#> 
#> P value adjustment: tukey method for comparing a family of 2.56155281280883 estimates

# allow.na.levs = FALSE
options(emmeans = list(allow.na.levs = FALSE))
em3 <- emmeans(m, ~ group)
contrast(em3, "pairwise")
#>  contrast estimate    SE df t.ratio p.value
#>  a - b          -2 0.707  2  -2.828  0.1056
em4 <- emmeans(m, ~ group, data = x)
contrast(em4, "pairwise")
#>  contrast estimate    SE df t.ratio p.value
#>  a - b          -2 0.707  2  -2.828  0.1056
```

<sup>Created on 2024-09-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

## Expected behavior
I would expect the previous behaviour (i.e. no `c` contrasts regardless of using `data` or not).

## Additional context
I would suggest having a test for such case (something along the lines of the example).

### PR DESCRIPTION
**Pull request by banfai**
Closes #508 

Solution from https://stackoverflow.com/a/78719672

### CODE REVIEW

**Comment by rvlenth** [comment]
OK, I have look at this as well as the tests in #500, and think this is the right fix for the problem.

**Comment by banfai** [comment]
thanks a lot for the quick review

**Comment by rvlenth** [comment]
PS -- I added tests for the case where we *allow* factors to have `NA` levels:
```
# Missing and NA levels
miss.df = data.frame(x = factor(c("a", "a", "b", NA), levels = c("a", "b", "c", NA)), y = 1:4)
miss.lm = lm(y ~ x, data = miss.df)
miss.rg1 = ref_grid(miss.lm)
miss.rg2 = ref_grid(miss.lm, data = miss.df)
# Now try allowing NA levels
miss.dfa = transform(miss.df, x = factor(x, exclude = NULL))
miss.lma = lm(y ~ x, data = miss.dfa)
miss.rg1a = ref_grid(miss.lma)
miss.rg2a = ref_grid(miss.lma, data = miss.dfa)
test_that("Reference grid handles missing values", {
    expect_equal(length(miss.rg1@levels$x), 2)
    expect_equal(length(miss.rg2@levels$x), 2)
    expect_equal(length(miss.rg1a@levels$x), 3)
    expect_equal(length(miss.rg2a@levels$x), 3)
    emm_options(allow.na.levs = FALSE)
    expect_error(ref_grid(miss.lma))
    emm_options(allow.na.levs = NULL) # revert to default
})
```
Happy to say they all pass!

Thanks for the contribution!

**Comment by rvlenth** [comment]
Please confirm that this is correct for you in the DESCRIPTION file:
```
    person("Balasz", "Banfai", role = "ctb"),
```

**Comment by banfai** [comment]
> Please confirm that this is correct for you in the DESCRIPTION file:
> 
> ```
>     person("Balasz", "Banfai", role = "ctb"),
> ```
z and s are the other way around:
```
    person("Balazs", "Banfai", role = "ctb"),
```


> PS -- I added tests for the case where we _allow_ factors to have `NA` levels:
> Happy to say they all pass!
> Thanks for the contribution!
That's great, thanks for expanding the tests. Happy to contribute to this amazing package!

**Pull request merged**
